// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlite

import ()

type Account struct {
	UserNumber   string
	TwilioNumber string
	DiscordToken string
}

type ChannelSerial struct {
	UserID    int64
	ChannelID int64
	Serial    int64
}

type NumbersMuted struct {
	UserNumber string
	Muted      int64
}
