// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import ()

type Message struct {
	ID           int64
	ToNumber     string
	CreatedAt    int64
	ProtobufData []byte
}
